const FRONTEND_TYPE_INPUT = 1;
const FRONTEND_TYPE_TEXT = 2;
const FRONTEND_TYPE_CHECK_BOX = 3;
const FRONTEND_TYPE_RADIO = 4;
const FRONTEND_TYPE_SELECT = 5;
const FRONTEND_TYPE_GRID_RADIO = 6;
const FRONTEND_TYPE_GRID_CHECK_BOX = 7;
const FRONTEND_TYPE_DATE = 8;
const FRONTEND_TYPE_DATETIME = 9;

export default {
    FRONTEND_TYPE_INPUT: FRONTEND_TYPE_INPUT,
    FRONTEND_TYPE_TEXT: FRONTEND_TYPE_TEXT,
    FRONTEND_TYPE_CHECK_BOX: FRONTEND_TYPE_CHECK_BOX,
    FRONTEND_TYPE_RADIO: FRONTEND_TYPE_RADIO,
    FRONTEND_TYPE_SELECT: FRONTEND_TYPE_SELECT,
    FRONTEND_TYPE_GRID_RADIO: FRONTEND_TYPE_GRID_RADIO,
    FRONTEND_TYPE_GRID_CHECK_BOX: FRONTEND_TYPE_GRID_CHECK_BOX,
    FRONTEND_TYPE_DATE: FRONTEND_TYPE_DATE,
    FRONTEND_TYPE_DATETIME: FRONTEND_TYPE_DATETIME,
}
